//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinMM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinMM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;devices&gt;
        ///&lt;manufacturer id=&quot;1&quot; name=&quot;Microsoft Corporation&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;2&quot; name=&quot;Creative Labs, Inc&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;3&quot; name=&quot;Media Vision, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;4&quot; name=&quot;Fujitsu Corp.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;20&quot; name=&quot;Artisoft, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;21&quot; name=&quot;Turtle Beach, Inc.&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot;22&quot; name=&quot;IBM Corporation&quot;&gt;&lt;/manufacturer&gt;
        ///&lt;manufacturer id=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
    }
}
